namespace Telegram.Bot.Types
{
    /// <summary>
    /// This object represents a video message (available in Telegram apps as of v.4.0).
    /// </summary>
    //[JsonObject(MemberSerialization.OptIn, NamingStrategyType = typeof(SnakeCaseNamingStrategy))]
    public sealed record VideoNote : FileBase,
        IAutoGeneratedVideoNote
    {
        /// <summary>
        /// Video width and height as defined by sender
        /// </summary>
        //[JsonProperty(Required = Required.Always)]
        public int Length { get; init; }

        /// <summary>
        /// Duration of the video in seconds as defined by sender
        /// </summary>
        //[JsonProperty(Required = Required.Always)]
        public int Duration { get; init; }

        /// <summary>
        /// Optional. Video thumbnail
        /// </summary>
        //[JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        public PhotoSize Thumb { get; init; }
    }
}
